import { gql } from '@apollo/client';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { Coins, MapPin, Translate } from 'phosphor-react';
import pluralize from 'pluralize';
import client from '../../apollo-client';
import BackButton from '../../components/BackButton';
import Title from '../../components/Title';

interface Language {
  code: string;
  name: string;
}

interface Country {
  name: string;
  capital: string;
  currency: string;
  languages: Language[];
}

interface Props {
  country: Country;
}

export const GET_COUNTRY_BY_ID = gql`
  query Country($code: ID!) {
    country(code: $code) {
      name
      capital
      currency
      languages {
        code
        name
      }
    }
  }
`;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query;

  const { data } = await client.query({
    query: GET_COUNTRY_BY_ID,
    variables: {
      code: id,
    },
  });

  return {
    props: {
      country: data.country,
    },
  };
};

const Country: NextPage<Props> = ({ country }) => {
  return (
    <>
      <Head>
        <title>{country.name}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div>
        <BackButton />
        <Title as="h1">{country.name}</Title>
        <div className="flex w-full justify-between pt-6">
          <div className="flex gap-2">
            <MapPin size={32} />
            <div>
              <div className="font-medium capitalize">capital</div>
              <div>{country.capital}</div>
            </div>
          </div>

          <div className="flex gap-2">
            <Coins size={32} />
            <div>
              <div className="font-medium capitalize">currency</div>
              <div>{country.currency}</div>
            </div>
          </div>

          <div className="flex gap-2">
            <Translate size={32} />
            <div>
              <div className="font-medium capitalize">
                {pluralize('language', country.languages.length)}
              </div>
              {country.languages.map((language) => (
                <div key={language.code}>{language.name}</div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Country;
