import { gql } from '@apollo/client';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import client from '../apollo-client';
import ContainerLayout from '../components/ContainerLayout';
import Heading from '../components/Heading';
import Item from '../components/Item';

interface Continents {
  code: string;
  name: string;
}

interface Props {
  continents: Continents[];
}

export const GET_ALL_CONTINENTS = gql`
  query Continents {
    continents {
      code
      name
    }
  }
`;

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await client.query({
    query: GET_ALL_CONTINENTS,
  });

  return {
    props: {
      continents: data.continents,
    },
  };
};

const Home: NextPage<Props> = ({ continents }) => {
  return (
    <>
      <Head>
        <title>Continents</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <Heading text="continents" />

      <ContainerLayout>
        {continents.map((continent) => (
          <Item
            key={continent.code}
            href={`/continents/${continent.code}`}
            text={continent.name}
          />
        ))}
      </ContainerLayout>
    </>
  );
};

export default Home;
